//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SudokuSolverLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SudokuSolverLib.stringResources", typeof(stringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial storage size must be a positive number.
        /// </summary>
        internal static string Heap_InitialStorageMustBePositive {
            get {
                return ResourceManager.GetString("Heap_InitialStorageMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No elements in the heap.
        /// </summary>
        internal static string Heap_NoElements {
            get {
                return ResourceManager.GetString("Heap_NoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hints count.
        /// </summary>
        internal static string Puzzle_InvalidHintsCount {
            get {
                return ResourceManager.GetString("Puzzle_InvalidHintsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a mismatch between the size of the grid and the nodes identified in the puzzle.
        /// </summary>
        internal static string Puzzle_MismatchBetweenGridSizeAndPuzzleNodes {
            get {
                return ResourceManager.GetString("Puzzle_MismatchBetweenGridSizeAndPuzzleNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have a negative or zero puzzle size.
        /// </summary>
        internal static string Puzzle_NoNegativePuzzleSize {
            get {
                return ResourceManager.GetString("Puzzle_NoNegativePuzzleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have a puzzle box size larger than 5x5.
        /// </summary>
        internal static string Puzzle_NoPuzzleBoxLargerThan5 {
            get {
                return ResourceManager.GetString("Puzzle_NoPuzzleBoxLargerThan5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle cannot be empty.
        /// </summary>
        internal static string Puzzle_PuzzleCannotBeEmpty {
            get {
                return ResourceManager.GetString("Puzzle_PuzzleCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character &apos;{0}&apos; while parsing puzzle (line {1} col {2}).
        /// </summary>
        internal static string Puzzle_UnexpectedCharacterWhileParsing {
            get {
                return ResourceManager.GetString("Puzzle_UnexpectedCharacterWhileParsing", resourceCulture);
            }
        }
    }
}
